<a href="https://colab.research.google.com/github/teyaa01/Linear-Algebra_2nd-Sem/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 2: Matrices

### Objectives

## Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices


The notation and use of matrices is  probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundrends and thousands of them. ## [have your own discussion]






## Let's say for example you have ***A*** and ***B*** as system of equation. 

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
      w-2x+3y-4z \\
      3w- x -2y +z \\
      2w -x + 3y - 2Z
    \end{array}
\right. $$


We could see that ***A*** is a system of 2 equations with 2 parameters. While ***B*** is a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix} \\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix} \\
$$


nasa ss

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


nasa ss

In [18]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [5]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [6]:
G = np.array([
    [1,2,3],
    [2,2,4]
])
describe_mat(G)

Matrix:
[[1 2 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [10]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8,2],
    [5,4],
    [1,1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [9]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



According to shape



 Row and Column Matrices

nasa ss

In [75]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    [1,3,2,-4]
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3,-4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)



Matrix:
[[ 1  3  2 -4]]

Shape:	(1, 4)
Rank:	2
Is Square: False

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2
Is Square: False



In [17]:
## Declaring a Column Matrix

col_mat = np.array([
    [300],
    [9],
    [7]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[300]
 [  9]
 [  7]]

Shape:	(3, 1)
Rank:	2



Square Matrices

nasa recording

In [23]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [25]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



According to element values


## Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix

In [26]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [32]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [33]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


Ones Matrix

A ones matrix, just like the zero matrix, canbe any rectangular matrix but all of its elemnts are 1s instead of 0s.

In [37]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


Diagonal Matrix

A diagonal

In [39]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a [1,1], a[2,2], a[3,3], ... a[n-1, n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [40]:
d = np.diag([2,3,5,7])
d.shape[0] == d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Upper Triangular Matrix

An upper triangular matrix is a matrix

In [48]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])      

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [49]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])      
])      

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

Practice

1. Given the linear combination below, try to create a corresponding matrix representing it. 

:$$\theta = 5x + 3y - z$$


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown



In [50]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.



In [51]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

Addition

In [52]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [54]:
3+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[4, 5],
       [5, 6],
       [7, 4]])

Subtraction

In [55]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [56]:
3-B

array([[1, 1],
       [3, 3],
       [2, 2]])

Element-wise Multiplication

In [57]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [58]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

# Activity

## Task 1