<a href="https://colab.research.google.com/github/teyaa01/Linear-Algebra_2nd-Sem/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE

## Laboratory 6 : Matrix Operations




Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives

At the end of this activity you will be able to:


1.   Be familiar with the fundamental matrix operations.

2.   Apply the operations to solve intemrediate equations.

3. Apply matrix algebra in engineering solutions










## Discussion

Importing mathematical functionalities are essential in order to easily operate matrix operations. Below are the functions needed for this laboratory:
  

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$  its transpose is denoted as $A^T$. So for example:



$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.


In [ ]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

#### Try to create your own matrix (you can try non-squares) to test transposition.

In [ ]:
D = np.array([
    [2,5,4,6],
    [3,0,6,4]
])
D.shape

(2, 4)

In [ ]:
D.T.shape

(4, 2)

In [ ]:
C = np.array([
    [2,6,5],
    [6,7,8],
    [6,1,2]
])
C.shape

(3, 3)

In [ ]:
C.T.shape

(3, 3)

## Dot Product / Inner Product

Dot product multiplies two matrices with the condition that the number of columns of the first matrix is equal to the number of rows of the second matrix. Given below are matrices $O$ and $P$ with sizes 2✕2 and 2✕3, respectively.

$$O = \begin{bmatrix}o_{(0,0)}&o_{(0,1)}\\ o_{(1,0)}&o_{(1,1)}\end{bmatrix}, P = \begin{bmatrix}p_{(0,0)}&p_{(0,1)}\\ p_{(1,0)}&p_{(1,1)}\end{bmatrix}$$

It will be multiplied using the row-column technique and will then be computed as:


$$O \cdot P= \begin{bmatrix} o_{(0,0)}*p_{(0,0)} + o_{(0,1)}*p_{(1,0)} & o_{(0,0)}*p_{(0,1)} + o_{(0,1)}*p_{(1,1)} \\  o_{(1,0)}*p_{(0,0)} + o_{(1,1)}*p_{(1,0)} & o_{(1,0)}*p_{(0,1)} + o_{(1,1)}*p_{(1,1)}
\end{bmatrix}$$


So assigning values to $O$ and $P$:
$$O = \begin{bmatrix}3&7\\ 2&1\end{bmatrix}, P = \begin{bmatrix}-8&1\\ 3&1\end{bmatrix}$$

The output/ answer will be:


$$O \cdot P= \begin{bmatrix} 3*-8 + 7*3 & 3*1 + 7*1 \\  2*-8 + 1*3 & 2*1 + 1*1 \end{bmatrix} = \begin{bmatrix} -3 & 10 \\-13 & 3 \end{bmatrix}$$

In Python, it can be programmed using three different codes, such as `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [ ]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X @ Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
A = np.array([
    [1,2],
    [0,1]
])
B = np.array([
    [-1,0,5],
    [2,6,7],
])

In [ ]:
A @ B

array([[ 3, 12, 19],
       [ 2,  6,  7]])

In [ ]:
np.dot(A,B)

array([[ 3, 12, 19],
       [ 2,  6,  7]])

In [ ]:
np.matmul(A,B)

array([[ 3, 12, 19],
       [ 2,  6,  7]])

In [ ]:
A.dot(B)

array([[ 3, 12, 19],
       [ 2,  6,  7]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:


### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\\1&7\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\0&5\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1&2&6\\1&1&2&4&8\end{bmatrix}$$

So in this case $A$ has a shape of $(4,2)$, $B$ has a shape of $(4,2)$ and $C$ has a shape of $(2,5)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

code the above like the code below

In [ ]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1],
    [1,7]
])
B = np.array([
    [1,1],
    [3,3],
    [0,5],
    [-1,-2]
])
C = np.array([
    [0,1,1,2,6],
    [1,1,2,4,8]
])
print(A.shape)
print(B.shape)
print(C.shape)

(4, 2)
(4, 2)
(2, 5)


In [ ]:
A @ C

array([[ 4,  6, 10, 20, 44],
       [-2,  3,  1,  2, 14],
       [ 1,  1,  2,  4,  8],
       [ 7,  8, 15, 30, 62]])

In [ ]:
B @ C

array([[  1,   2,   3,   6,  14],
       [  3,   6,   9,  18,  42],
       [  5,   5,  10,  20,  40],
       [ -2,  -3,  -5, -10, -22]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
A @ B.T

array([[  6,  18,  20, -10],
       [  3,   9, -10,  -1],
       [  1,   3,   5,  -2],
       [  8,  24,  35, -15]])

In [ ]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 



In [ ]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,0]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant


A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
O = np.array([
    [1,2,3,4],
    [5,12,7,0],
    [9,1,11,12],
    [13,4,1,6]
])
np.linalg.det(O)

-4199.999999999993

try bigger matrices. this save time to solve

In [ ]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

## Inverse

The inverse of a matrix is simply the reciprocal of the matrix. When the inverse of a matrix is multiplied with its original matrix, it will yield to an identity matrix. Additionally,  the inverse of a matrix also helps in determining its solvability and characteristics as a linear equation, as well as solving the problem of divisibility between matrices. It provides related operations that have the same concept of dividing matrices.

Here are the steps to determine the inverse of a matrix. Starting with a matrix $S$:
$$S = \begin{bmatrix}1&4\\3&2\end{bmatrix}$$

First, we need to get the determinant of $S$.

$$|S| = (1)(2)-(4)(3) = -10$$

Next, we need to reform the matrix into the inverse form:

$$S^{-1} = \frac{1}{|S|} \begin{bmatrix} s_{(1,1)} & -s_{(0,1)} \\ -s_{(1,0)} & s_{(0,0)}\end{bmatrix}$$

So that will be:
$$S^{-1} = \frac{1}{-10} \begin{bmatrix} 2 & -4 \\ -3 & 1\end{bmatrix} = \begin{bmatrix} \frac{-1}{5} & \frac{2}{5} \\ \frac{3}{10} & \frac{-1}{10}\end{bmatrix}$$

For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
S = np.array([
    [1,4],
    [3, 2]
])

np.array(S @ np.linalg.inv(S), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
    [3,8,1],
    [4,8,9],
    [2,-6,0]
])
V = np.linalg.inv(P)
V

array([[ 0.20300752, -0.02255639,  0.2406015 ],
       [ 0.06766917, -0.0075188 , -0.08646617],
       [-0.15037594,  0.12781955, -0.03007519]])

In [ ]:
P @ V

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the whether the matrix that you have solved is really the inverse, we follow this dot product property for a matrix $S$:
$$S\cdot S^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.
1. $A \cdot B \neq B \cdot A$
2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
3. $A\cdot(B+C) = A\cdot B + A\cdot C$
4. $(B+C)\cdot A = B\cdot A + C\cdot A$
5. $A\cdot I = A$
6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
    [4,7,2],
    [0,-2,0],
    [3,5,1],     
])

B = np.array([
    [-5,0,4],
    [2,1,3],
    [5,1,4],         
])

C = np.array([
    [5,-4,0],
    [9,2,-7],
    [1,4,3],         
])

1. $A \cdot B \neq B \cdot A$


In [ ]:
Zack = A @ B
Zack

array([[ 4,  9, 45],
       [-4, -2, -6],
       [ 0,  6, 31]])

In [ ]:
Tabudlo = B @ A
Tabudlo

array([[ -8, -15,  -6],
       [ 17,  27,   7],
       [ 32,  53,  14]])

In [ ]:
np.array_equal(Zack,Tabudlo)

False

2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$


In [ ]:
Converse = A @ (B @ C)
Converse

array([[146, 182,  72],
       [-44, -12,  -4],
       [ 85, 136,  51]])

In [ ]:
High = (A @ B) @ C
High

array([[146, 182,  72],
       [-44, -12,  -4],
       [ 85, 136,  51]])

In [ ]:
np.array_equal(Converse,High)

True

3. $A\cdot(B+C) = A\cdot B + A\cdot C$


In [ ]:
HELLO = A @ (B + C)
HELLO

array([[ 89,  15,   2],
       [-22,  -6,   8],
       [ 61,   8,  -1]])

In [ ]:
WORLD = A @ B + A @ C
WORLD

array([[ 89,  15,   2],
       [-22,  -6,   8],
       [ 61,   8,  -1]])

In [ ]:
np.array_equal(HELLO,WORLD)

True

4. $(B+C)\cdot A = B\cdot A + C\cdot A$


In [ ]:
Miss = (B + C) @ A
Miss

array([[12, 28,  4],
       [32, 51, 18],
       [45, 67, 19]])

In [ ]:
Right = B @ A + C @ A
Right

array([[12, 28,  4],
       [32, 51, 18],
       [45, 67, 19]])

In [ ]:
np.array_equal(Miss,Right)

True

5. $A\cdot I = A$


In [ ]:
CUTE = np.identity(3)
CUTE

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
AKO = A.dot(np.identity(3))
AKO

array([[ 4.,  7.,  2.],
       [ 0., -2.,  0.],
       [ 3.,  5.,  1.]])

In [ ]:
np.array_equal(A, AKO) 

True

6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
Spring = np.zeros(A.shape)
Spring

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Day = A.dot(np.zeros(A.shape))
Day

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(Spring, Day)

True

## Conclusion

The laboratory activity gave students an opportunity to master Python fundamentals particularly concerning operations on matrices. It is in this module that Transposition, Dot Product, Rules on Matrix Operations, Determinant, Inverse, and Properties on Matrix Multiplication is learned and analyzed. At the end of the module, users are able to produce an output that proves the validity of the Properties on Matrix Multiplication by giving concrete example of codes. 
 
Matrix operations and properties are essential topics to be mastered not only in Programming courses but also in different fields. Specifically, matrix operations are also used in the medical field as the new generation of information technology uses matrix operations in developing systems that further adapt to modern day technology. Matrix operations are used as a solution to the growing problems of database, organization, and framework in the healthcare industry. Without matrix operations, the jobs needed to perform by healthcare professionals each day are doubled or further delayed due to slow process.
